version: "3.3"

services:
  postgres:
    container_name: postgres
    build: ./postgres
    restart: always
    ports:
      - "5000:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - bakeland

  endpoints:
    container_name: endpoint
    build: ./endpoint
    ports:
      - "8000:8080"
    volumes:
      - ./.env:/app/.env
    restart: always
    depends_on:
      - postgres
    networks: 
     - bakeland

  wormhole:
    container_name: wormhole
    build: ./wormhole
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/usr/src/app/.env
    restart: always
    networks: 
     - bakeland

  monitoring:
    container_name: monitoring
    build: ./monitoring
    ports:
      - "4000:4000"
    volumes:
      - ./.env:/usr/src/app/.env
    restart: always
    networks: 
     - bakeland

  heymint:
    container_name: heymint
    build: ./heyMint
    ports:
      - "6000:6000"
    volumes:
      - ./.env:/usr/src/app/.env
    restart: always
    depends_on:
      - postgres
    networks: 
     - bakeland

networks:
  bakeland:
    driver: bridge
