version: "3.8"

services:
  endpoints:
    container_name: endpoint
    build: ./endpoint
    ports:
      - "8000:8080"
    volumes:
      - ./.env:/app/.env
    restart: always
    depends_on:
      - postgres
    networks: 
     - bakeland

  wormhole:
    container_name: wormhole
    build: ./wormhole
    ports:
      - "3000:3001"
    volumes:
      - ./.env:/usr/src/app/.env
    restart: always
    networks: 
     - bakeland
  
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5000:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - bakeland

networks:
  bakeland:
    driver: bridge
